In [8]:
pip install pandasql

Requirement already satisfied: pandasql in c:\users\sony\anaconda3\lib\site-packages (0.7.3)
Requirement already satisfied: sqlalchemy in c:\users\sony\anaconda3\lib\site-packages (from pandasql) (1.4.32)
Requirement already satisfied: pandas in c:\users\sony\anaconda3\lib\site-packages (from pandasql) (1.4.2)
Requirement already satisfied: numpy in c:\users\sony\anaconda3\lib\site-packages (from pandasql) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sony\anaconda3\lib\site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sony\anaconda3\lib\site-packages (from pandas->pandasql) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\sony\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas->pandasql) (1.16.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sony\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Importing the libraries 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# Ignore harmless warnings 

import warnings 
warnings.filterwarnings("ignore")

# Set to display all the columns in dataset

pd.set_option("display.max_columns", None)

# Import psql to run queries 

import pandasql as psql

In [5]:
# Load the Whole Sale Customer data

zomatodata = pd.read_csv(r"C:\Users\SONY\Downloads\HyderabadResturants.csv", header=0)

# Copy the file to back-up file

zomatodata_bk = zomatodata.copy()

# display first 5 records

zomatodata.head()

,links,names,ratings,cuisine,price for one
0,https://www.zomato.com/hyderabad/sahara-bakers...,Sahara Bakers,3.7,"Chinese, Bakery, Sichuan, Pizza, Burger",100
1,https://www.zomato.com/hyderabad/kfc-abids/order,KFC,3.9,"Burger, Fast Food, Biryani, Desserts, Beverages",100
2,https://www.zomato.com/hyderabad/subbaiah-gari...,Subbaiah Gari Hotel,4.1,"South Indian, Andhra, Mithai",100
3,https://www.zomato.com/hyderabad/paradise-biry...,Paradise Biryani,3.9,"Biryani, Kebab, Desserts, Beverages",100
4,https://www.zomato.com/hyderabad/pista-house-b...,Pista House Bakery,4.3,"Fast Food, Sandwich, Pizza, Burger, Wraps, Rol...",100

In [6]:
zomatodata.isnull().sum()

links            0
names            0
ratings          0
cuisine          0
price for one    0
dtype: int64

In [7]:
zomatodata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 657 entries, 0 to 656
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   links          657 non-null    object
 1   names          657 non-null    object
 2   ratings        657 non-null    object
 3   cuisine        657 non-null    object
 4   price for one  657 non-null    int64
dtypes: int64(1), object(4)
memory usage: 25.8+ KB

In [8]:
zomatodata.nunique()

links            657
names            636
ratings           24
cuisine          396
price for one      8
dtype: int64

In [9]:
zomatodata['ratings'] = zomatodata['ratings'].replace('New','0').replace('-','0').astype('float')
zomatodata.ratings.unique()

array([3.7, 3.9, 4.1, 4.3, 4. , 4.2, 4.4, 4.5, 3.8, 4.6, 3.6, 0. , 3.4,
       3.5, 3.1, 3.3, 2.7, 3.2, 3. , 4.7, 2.8, 2.9, 2.6])

In [10]:
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

zomatodata['links'] = LE.fit_transform(zomatodata[['links']])
zomatodata['names'] = LE.fit_transform(zomatodata[['names']])
zomatodata['cuisine'] = LE.fit_transform(zomatodata[['cuisine']])

In [11]:
zomatodata.head()

   links  names  ratings  cuisine  price for one
0    472    455      3.7      131            100
1    302    290      3.9       94            100
2    555    535      4.1      349            100
3    423    406      3.9       78            100
4    430    413      4.3      194            100

In [12]:
zomatodata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 657 entries, 0 to 656
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   links          657 non-null    int32
 1   names          657 non-null    int32
 2   ratings        657 non-null    float64
 3   cuisine        657 non-null    int32
 4   price for one  657 non-null    int64
dtypes: float64(1), int32(3), int64(1)
memory usage: 18.1 KB

In [13]:
# Identify the Independent and Target variables

IndepVar = []
for col in zomatodata.columns:
    if col != 'ratings':
        IndepVar.append(col)

TargetVar = 'ratings'

x = zomatodata[IndepVar]
y = zomatodata[TargetVar]

In [14]:
# Split the data into train and test (random sampling)

from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [15]:
CSResults = pd.read_csv(r"C:\Users\SONY\Downloads\HTResults.csv", header=0)

In [16]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\sony\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy in c:\users\sony\anaconda3\lib\site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in c:\users\sony\anaconda3\lib\site-packages (from xgboost) (1.7.3)
Note: you may need to restart the kernel to use updated packages.

In [19]:
# Build the Regression / Regressor models

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import ExtraTreesRegressor

from sklearn.ensemble import GradientBoostingRegressor

# Create objects of Regression / Regressor models with default hyper-parameters

modelmlg = LinearRegression()
modeldcr = DecisionTreeRegressor()
modelrfr = RandomForestRegressor()
modelSVR = SVR()
modelXGR = xgb.XGBRegressor()
modelKNN = KNeighborsRegressor(n_neighbors=5)
modelETR = ExtraTreesRegressor()

modelGBR = GradientBoostingRegressor(loss='ls', learning_rate=0.1, n_estimators=100, subsample=1.0,
                                     criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1,
                                     min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0,
                                     min_impurity_split=None, init=None, random_state=None, max_features=None,
                                     alpha=0.9, verbose=0, max_leaf_nodes=None, warm_start=False,
                                     validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)

# Evalution matrix for all the algorithms

MM = [modelmlg, modeldcr, modelrfr, modelSVR, modelXGR, modelKNN, modelETR, modelGBR]

for models in MM:
    
    # Fit the model with train data
    
    models.fit(x_train, y_train)
    
    # Predict the model with test data

    y_pred = models.predict(x_test)
    
    # Print the model name
    
    print('Model Name: ', models)
    
    # Evaluation metrics for Regression analysis

    from sklearn import metrics

    print('Mean Absolute Error (MAE):', round(metrics.mean_absolute_error(y_test, y_pred),3))  
    print('Mean Squared Error (MSE):', round(metrics.mean_squared_error(y_test, y_pred),3))  
    print('Root Mean Squared Error (RMSE):', round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))
    print('R2_score:', round(metrics.r2_score(y_test, y_pred),6))
    print('Root Mean Squared Log Error (RMSLE):', round(np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),3))
    
    # Define the function to calculate the MAPE - Mean Absolute Percentage Error

    def MAPE (y_test, y_pred):
        y_test, y_pred = np.array(y_test), np.array(y_pred)
        return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    
    # Evaluation of MAPE 

    result = MAPE(y_test, y_pred)
    print('Mean Absolute Percentage Error (MAPE):', round(result, 2), '%')
    
    # Calculate Adjusted R squared values 

    r_squared = round(metrics.r2_score(y_test, y_pred),6)
    adjusted_r_squared = round(1 - (1-r_squared)*(len(y)-1)/(len(y)-x.shape[1]-1),6)
    print('Adj R Square: ', adjusted_r_squared)
    print('------------------------------------------------------------------------------------------------------------')
    #-------------------------------------------------------------------------------------------
    new_row = {'Model Name' : models,
               'Mean_Absolute_Error_MAE' : metrics.mean_absolute_error(y_test, y_pred),
               'Adj_R_Square' : adjusted_r_squared,
               'Root_Mean_Squared_Error_RMSE' : np.sqrt(metrics.mean_squared_error(y_test, y_pred)),
               'Mean_Absolute_Percentage_Error_MAPE' : result,
               'Mean_Squared_Error_MSE' : metrics.mean_squared_error(y_test, y_pred),
               'Root_Mean_Squared_Log_Error_RMSLE': np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),
               'R2_score' : metrics.r2_score(y_test, y_pred)}
    CSResults = CSResults.append(new_row, ignore_index=True)

TypeError: __init__() got an unexpected keyword argument 'min_impurity_split'

In [16]:
CSResults.head()

,Model_Name,True_Positive,False_Negative,False_Positive,True_Negative,Accuracy,Precision,Recall,F1 Score,Specificity,MCC,ROC_AUC_Score,Balanced Accuracy,Adj_R_Square,Mean_Absolute_Error_MAE,Mean_Absolute_Percentage_Error_MAPE,Mean_Squared_Error_MSE,Model Name,R2_score,Root_Mean_Squared_Error_RMSE,Root_Mean_Squared_Log_Error_RMSLE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002781,0.747396,inf,1.384471,LinearRegression(),0.003334,1.176636,0.162659
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.112010,0.972222,NaN,2.915909,DecisionTreeRegressor(),-1.099132,1.707603,0.535091
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.126626,0.829182,inf,1.555455,"(DecisionTreeRegressor(max_features='auto', ra...",-0.119756,1.247179,0.220884
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.091890,0.613407,inf,1.507498,SVR(),-0.085232,1.227802,0.205226
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.516095,0.915611,inf,2.093170,"XGBRegressor(base_score=0.5, booster='gbtree',...",-0.506851,1.446779,0.369340